spring.application.name=sukusuku
spring.web.resources.static-locations=classpath:/static/,classpath:/assets/,classpath:/home_static/

# ?? ???? ???? ??? ??, ???? ???? ??? ??
#spring.jpa.hibernate.ddl-auto=validate

# Hibernate DDL ???? ? ??!(?? ?? ?? ?? SQL? ??)
# ??? ?? ??/????
spring.jpa.hibernate.ddl-auto=update

# ???? ?? ?? ??
#spring.jpa.show-sql=true
# ?? ?? ???
#spring.jpa.properties.hibernate.format_sql=true
