spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/post
    username: root
    password: '00000000'
  jpa:
    hibernate:
      ddl-auto: update
      